// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDd1Xn5SWmqn0w7Zv3dzD-8-4oarapEWww',
    appId: '1:219546401140:web:ac6e283e2268d414e81421',
    messagingSenderId: '219546401140',
    projectId: 'fluttertask-87700',
    authDomain: 'fluttertask-87700.firebaseapp.com',
    storageBucket: 'fluttertask-87700.appspot.com',
    measurementId: 'G-D534J09JTW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPF2UIjRhsG9I85_dEXc-rz0zam5tWCqI',
    appId: '1:219546401140:android:28454f79041c3ae0e81421',
    messagingSenderId: '219546401140',
    projectId: 'fluttertask-87700',
    storageBucket: 'fluttertask-87700.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXo-8VPlETTAn-6Kqmg9SQ4yUBHI0HWls',
    appId: '1:219546401140:ios:a8810f8c8b6b8a82e81421',
    messagingSenderId: '219546401140',
    projectId: 'fluttertask-87700',
    storageBucket: 'fluttertask-87700.appspot.com',
    iosBundleId: 'com.example.fluttertask',
  );
}
